# banking -*- mode: org -*-
#+TODO: TODO(t) STARTED(s) WAITING(w) | DONE(d) CANCELLED(c)
#+STARTUP: overview logdone

* debian trixie
We install debian trixie, stable.

gargle@p14:~/pandora$ cat /etc/debian_version
13.1

root@p14:~# ls /etc/apt/sources.list
/etc/apt/sources.list

root@p14:~# cat /etc/apt/sources.list
#deb cdrom:[Debian GNU/Linux 13.1.0 _Trixie_ - Official amd64 NETINST with firmware 20250906-10:22]/ trixie contrib main non-free-firmware

deb http://ftp.be.debian.org/debian/ trixie main non-free-firmware
deb-src http://ftp.be.debian.org/debian/ trixie main non-free-firmware

deb http://security.debian.org/debian-security trixie-security main non-free-firmware
deb-src http://security.debian.org/debian-security trixie-security main non-free-firmware

# trixie-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://ftp.be.debian.org/debian/ trixie-updates main non-free-firmware
deb-src http://ftp.be.debian.org/debian/ trixie-updates main non-free-firmware

# This system was installed using removable media other than
# CD/DVD/BD (e.g. USB stick, SD card, ISO image file).
# The matching "deb cdrom" entries were disabled at the end
# of the installation process.
# For information about how to configure apt package sources,
# see the sources.list(5) manual.

* partitions
We start with only /boot/efi, /boot, and an encrypted lvm with / and /home.  Swap we define by means of zam.

gargle@p14:~$ lsblk
NAME                   MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
zram0                  253:0    0   6.8G  0 disk  [SWAP]
nvme0n1                259:0    0 476.9G  0 disk
├─nvme0n1p1            259:1    0   976M  0 part  /boot/efi
├─nvme0n1p2            259:2    0   977M  0 part  /boot
└─nvme0n1p3            259:3    0   475G  0 part
  └─nvme0n1p3_crypt    254:0    0   475G  0 crypt
    ├─p14--vg-lv--root 254:1    0  59.6G  0 lvm   /
    └─p14--vg-lv--home 254:2    0 415.4G  0 lvm   /home

* f1-f12 function keys
We tell the bios that f1-f12 are accessible without fnlock.

* networking
** lo and enp1s0f0
gargle@p14:~$ ls -haltr /etc/network/interfaces
-rw-r--r-- 1 root root 322 Oct  2 16:19 /etc/network/interfaces

gargle@p14:~$ ls -haltr /etc/network/interfaces.d
total 8.0K
drwxr-xr-x 2 root root 4.0K Sep 17  2024 .
drwxr-xr-x 7 root root 4.0K Oct  2 16:19 ..

gargle@p14:~$ cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp1s0f0
iface enp1s0f0 inet dhcp

** wlp2s0
*** wpa_supplicant
gargle@p14:~$ ls -haltr /etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf
-rw-r--r-- 1 root root 1.3K Oct  2 15:36 /etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf

gargle@p14:~$ head -n 5 /etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
        ssid="gargle"

*** systemd
gargle@p14:~$ ls -haltr /etc/systemd/network/wlp2s0.network
-rw-r--r-- 1 root root 41 Oct  2 14:46 /etc/systemd/network/wlp2s0.network

gargle@p14:~$ cat /etc/systemd/network/wlp2s0.network
[Match]
Name=wlp2s0

[Network]
DHCP=yes

root@p14:~# systemctl enable --now wpa_supplicant@wlp2s0.service

gargle@p14:~$ systemctl status wpa_supplicant@wlp2s0.service
● wpa_supplicant@wlp2s0.service - WPA supplicant daemon (interface-specific version)
     Loaded: loaded (/usr/lib/systemd/system/wpa_supplicant@.service; enabled; preset: enabled)
     Active: active (running) since Thu 2025-10-02 16:28:46 CEST; 7min ago
 Invocation: 1a36631e117c462d85391b52f25741a6
   Main PID: 1466 (wpa_supplicant)
      Tasks: 1 (limit: 33020)
     Memory: 9.5M (peak: 9.7M)
        CPU: 28ms
     CGroup: /system.slice/system-wpa_supplicant.slice/wpa_supplicant@wlp2s0.service
             └─1466 /usr/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-wlp2s0.conf -iwlp2s0

gargle@p14:~$ sudo wpa_cli status
Selected interface 'wlp2s0'
bssid=84:16:f9:59:66:5f
freq=5180
ssid=gargle
id=0
mode=station
wifi_generation=5
pairwise_cipher=CCMP
group_cipher=CCMP
key_mgmt=WPA2-PSK
wpa_state=COMPLETED
ip_address=192.168.1.122
p2p_device_address=12:e1:8e:84:b0:d2
address=10:e1:8e:84:b0:d2
uuid=ad074921-c6c5-5b79-a778-af489e4ba534
ieee80211ac=1

gargle@p14:~$ sudo wpa_cli reconfigure
Selected interface 'wlp2s0'
OK

* firewall
Just make sure IPV6=yes is on.

root@p14:~# ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

root@p14:~# systemctl status ufw.service
● ufw.service - Uncomplicated firewall
     Loaded: loaded (/usr/lib/systemd/system/ufw.service; enabled; preset: enabled)
     Active: active (exited) since Thu 2025-10-02 16:28:46 CEST; 20min ago
 Invocation: 5f3018ac923f443487d52e9a509d0339
       Docs: man:ufw(8)
   Main PID: 1223 (code=exited, status=0/SUCCESS)
   Mem peak: 3.7M
        CPU: 60ms

Oct 02 16:28:46 p14 systemd[1]: Starting ufw.service - Uncomplicated firewall...
Oct 02 16:28:46 p14 systemd[1]: Finished ufw.service - Uncomplicated firewall.

root@p14:~# cat /etc/default/ufw
# /etc/default/ufw
#

# Set to yes to apply rules to support IPv6 (no means only IPv6 on loopback
# accepted). You will need to 'disable' and then 'enable' the firewall for
# the changes to take affect.
IPV6=yes

# Set the default input policy to ACCEPT, DROP, or REJECT. Please note that if
# you change this you will most likely want to adjust your rules.
DEFAULT_INPUT_POLICY="DROP"

# Set the default output policy to ACCEPT, DROP, or REJECT. Please note that if
# you change this you will most likely want to adjust your rules.
DEFAULT_OUTPUT_POLICY="ACCEPT"

# Set the default forward policy to ACCEPT, DROP or REJECT.  Please note that
# if you change this you will most likely want to adjust your rules
DEFAULT_FORWARD_POLICY="DROP"

# Set the default application policy to ACCEPT, DROP, REJECT or SKIP. Please
# note that setting this to ACCEPT may be a security risk. See 'man ufw' for
# details
DEFAULT_APPLICATION_POLICY="SKIP"

# By default, ufw only touches its own chains. Set this to 'yes' to have ufw
# manage the built-in chains too. Warning: setting this to 'yes' will break
# non-ufw managed firewall rules
MANAGE_BUILTINS=no

#
# IPT backend
#
# only enable if using iptables backend
IPT_SYSCTL=/etc/ufw/sysctl.conf

# Extra connection tracking modules to load. IPT_MODULES should typically be
# empty for new installations and modules added only as needed. See
# 'CONNECTION HELPERS' from 'man ufw-framework' for details. Complete list can
# be found in net/netfilter/Kconfig of your kernel source. Some common modules:
# nf_conntrack_irc, nf_nat_irc: DCC (Direct Client to Client) support
# nf_conntrack_netbios_ns: NetBIOS (samba) client support
# nf_conntrack_pptp, nf_nat_pptp: PPTP over stateful firewall/NAT
# nf_conntrack_ftp, nf_nat_ftp: active FTP support
# nf_conntrack_tftp, nf_nat_tftp: TFTP support (server side)
# nf_conntrack_sane: sane support
IPT_MODULES=""

root@p14:~# ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

* swap
We install zram, use 25% of RAM max and use PRIORITY=100.

gargle@p14:~$ sudo apt install zram-tools

gargle@p14:~$ cat /etc/default/zramswap
# Compression algorithm selection
# speed: lz4 > zstd
# compression: zstd > lz4
# This is not inclusive of all that is available in latest kernels
# See /sys/block/zram0/comp_algorithm (when zram module is loaded) to see
# what is currently set and available for your kernel[1]
# [1]  https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html#select-compression-algorithm
ALGO=lz4

# Specifies the amount of RAM that should be used for zram
# based on a percentage the total amount of available memory
# This takes precedence and overrides SIZE below
PERCENT=25

# Specifies a static amount of RAM that should be used for
# the ZRAM devices, this is in MiB
SIZE=512

# Specifies the priority for the swap devices, see swapon(2)
# for more details. Higher number = higher priority
# This should probably be higher than hdd/ssd swaps.
PRIORITY=100

* keyboard

root@p14:~# cat /etc/default/keyboard
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT="altgr-weur"
#XKBOPTIONS="compose:lwin,ctrl:nocaps"
XKBOPTIONS="compose:lctrl,ctrl:nocaps"

BACKSPACE="guess"

gargle@p14:~$ sudo dpkg-reconfigure keyboard-configuration

gargle@p14:~$ sudo systemctl restart keyboard-setup.service

root@p14:~# setupcon

root@p14:~# update-initramfs -u

* background
gargle@p14:~$ ls -haltr /usr/share/WindowMaker/Backgrounds/Don-Quixote\ 1920x1200.jpg
-rw-rw-r-- 1 root root 161K Sep 30 15:10 '/usr/share/WindowMaker/Backgrounds/Don-Quixote 1920x1200.jpg'

* xdm
gargle@p14:~$ cat /etc/X11/xdm/Xsetup
#!/bin/sh
#
# This script is run as root before showing login widget.

/usr/bin/xli -onroot /usr/share/WindowMaker/Backgrounds/Don-Quixote\ 1920x1200.jpg

#xsetroot -solid rgb:8/8/8

* pcspkr
We disable the pcspeaker to get rid of the annoying BEEP in xterm and console.

root@p14:~# cat /etc/modprobe.d/pcspkr.conf
blacklist pcspkr

* led
We switch of the annoying led on F4 (mic mute LED).

root@p14:~# cat /etc/systemd/system/custom-startup.service
[Unit]
Description=Custom startup settings (mic mute LED)
After=local-fs.target
Wants=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/custom-startup.sh
TimeoutStartSec=10

[Install]
WantedBy=multi-user.target

root@p14:~# cat /usr/local/bin/custom-startup.sh
#!/bin/sh

# turn mic mute LED off
echo 0 > /sys/class/leds/platform::micmute/brightness 2>/dev/null || true

* TODO backports
https://ostechnix.com/enable-backports-testing-repositories-debian-13-trixie/
